- .eslintrc.js
- nodemon.json
- package-lock.json
- package.json
- src/arena/Constuructors/PhysConstructor.js
- src/arena/GameService.ts
- src/arena/OrderService.ts
- src/arena/RoundService.ts
- src/arena/magics/eclipse.ts
- src/helpers/channelHelper.ts
- src/models/item.ts
- tsconfig.json
* Добавил алиас для src
* Немного переделал RoundService:
* Объединил status и event в один status
* Заменил строки на enum
* Убрал глобальные флаги и eclipse (???) в GameService
> Add path alias, cleanup RoundService

- src/arena/BattleService.ts
- src/scenes/battle.ts
> Кнопки "Назад" в меню выбора цели и выборе силы умения (#63)

- .eslintrc.js
- src/arena/CharacterService.js
- src/arena/GameService.ts
- src/arena/MagicService.js
- src/arena/MatchMakingService.js
- src/cli/dev.ts
- src/cli/test.ts
- src/fwo.ts
- src/helpers/channelHelper.ts
- src/middlewares/protectedMiddleware.ts
- src/middlewares/restartMiddleware.ts
- src/scenes/battle.ts
- src/scenes/clan.ts
- src/scenes/create/create.ts
- src/scenes/createClan.ts
- src/scenes/greeter.ts
- src/scenes/harks.ts
- src/scenes/inventory.ts
- src/scenes/lobby.ts
- src/scenes/magics.ts
- src/scenes/profile.ts
- src/scenes/settings.ts
- src/scenes/shop/shop.ts
- src/scenes/skills.ts
> Fix scenes race conditions

- src/arena/engineService.ts
Я наконец решился понять что происходит в этом reduce, а там происходит groupBy просто
> Remove sortOrder method

- src/arena/BattleService.ts
- src/arena/CharacterService.js
- src/arena/MagicService.js
- src/arena/PlayersService/Player.ts
- src/arena/StatsService.ts
- src/helpers/BattleKeyboard.js
- src/models/character.ts
- src/scenes/battle.ts
- src/scenes/magics.ts
> Add favorite magics

- src/arena/CharacterService.js
> Fix free harks issue

- shop.json
- src/arena/BattleLog/utils/format-exp.ts
- src/arena/Constuructors/HealMagicConstructor.ts
Правки с хилом руками и мелкие правки кода
> handheal + small fixes

- src/arena/BattleLog/utils/format-error.ts
В старой арене писался target, но тут мы зачастую это опускаем, надо подумать нужна ли нам цель провала или пусть это будет закрытой инфой
> fix: breaks text

- src/arena/Constuructors/MagicConstructor.ts
- src/arena/magics/blessing.ts
- src/arena/magics/entangle.ts
- src/arena/magics/magicArmor.ts
- src/arena/magics/magicDefense.ts
- src/arena/magics/stoneSkin.ts
Правки с отображением CommonMagics #226
> Common Magic Effects

- src/arena/Constuructors/FlagsConstructor.ts
Правка с залипанием эффекта скилов обезоруживания и парирования
> fix: skill refresh

- src/arena/PlayersService/PlayersService.ts
- src/arena/magics/__snapshots__/chainLightning.test.ts.snap
- src/arena/magics/chainLightning.test.ts
- src/arena/magics/chainLightning.ts
И поправил -10% каждой цели. На вторую цель приходилось 100% урона
> Fix chainLightning not hitting non-clan targets

- src/arena/BattleService.ts
> #259 Fix multiple orders on same target

- package.json
- src/arena/CharacterService.js
- src/cli/resetHarks.ts
> #277 Fix harks saving

- src/arena/Constuructors/MagicConstructor.ts
> #272 Add effect modifier to common magic contructor

- src/arena/CharacterService.js
- src/arena/ClanService/ClanService.ts
- src/arena/PlayersService/PlayersService.test.ts
- src/scenes/clan.ts
> #276 Fix clan caching

- src/arena/Constuructors/HealMagicConstructor.ts
- src/arena/PlayersService/Player.ts
- src/arena/magics/heal.ts
> Reset the killer flag if a healing action saved the target's life

- src/arena/magics/physicalSadness.ts
> sadness fix

- src/arena/magics/__snapshots__/blight.test.ts.snap
- src/arena/magics/blight.test.ts
- src/arena/magics/blight.ts
- src/arena/magics/index.ts
> #149 Blight

- src/arena/Constuructors/PhysConstructor.js
- src/arena/MiscService.js
- src/arena/PlayersService/Player.ts
- src/arena/PlayersService/PlayerWeapon.ts
- src/arena/skills/dodge.ts
- src/arena/skills/parry.ts
> #258 Fix parrying range weapon

- src/arena/config.ts
- src/arena/magics/__snapshots__/bodySpirit.test.ts.snap
- src/arena/magics/bodySpirit.test.ts
- src/arena/magics/bodySpirit.ts
- src/arena/magics/index.ts
> #152 Body spirit

- src/arena/Constuructors/MagicConstructor.ts
- src/arena/Constuructors/utils/index.ts
- src/arena/GameService.ts
- src/arena/config.ts
- src/arena/magics/dustShield.ts
- src/arena/magics/index.ts
> #151 Dust shield

- src/arena/Constuructors/PhysConstructor.ts
- src/arena/Constuructors/types.ts
- src/arena/LogService/utils/format-error.ts
- src/arena/actions/__snapshots__/attack.test.ts.snap
- src/arena/actions/__snapshots__/handsHeal.test.ts.snap
- src/arena/actions/attack.test.ts
> #263 Phys cast chance

- src/arena/Constuructors/MagicConstructor.ts
- src/arena/Constuructors/utils/index.ts
- src/arena/LogService/LogService.ts
- src/arena/magics/anathema.ts
- src/arena/magics/dispel.ts
- src/arena/magics/exorcism.ts
- src/arena/magics/index.ts
- src/arena/magics/lightShield.ts
> #147 Exorcism, Anathema, Dispel

- client/components/ProtectedRoute.tsx
- client/hooks/useCharacterGuard.ts
- client/hooks/useGameGuard.ts
- client/hooks/useMount.ts
- client/hooks/useMountEffect.ts
- client/hooks/useSessionGuard.ts
- client/modules/game/components/GameAction.tsx
- client/modules/game/hooks/useGameKickState.ts
- client/modules/game/hooks/useGameState.ts
- server/arena/GameService.ts
- server/arena/OrderService.ts
- server/server/utils/activeConnectons.ts
- server/server/ws/game.ts
- shared/shared/message.ts
- Добавил возврат в игру в текущем состоянии
- Заменил в activeConnections значение id сокета на инстанс сокета, теперь reconnect срабатывает правильнее
> #359 Reconnect to the game

- server/arena/GameService.ts
> #363 Reduce gold for kill

- server/arena/Constuructors/HealMagicConstructor.ts
- server/arena/actions/__snapshots__/handsHeal.test.ts.snap
- server/arena/actions/handsHeal.test.ts
- server/arena/magics/heal.ts
> #381 Fix negative heal

- client/hooks/useCharacterGuard.ts
- client/hooks/useUpdateCharacter.ts
- client/modules/game/hooks/useGameState.ts
- server/arena/GameService.ts
- server/server/ws/game.ts
> #359 Fix game end behavior

- client/hooks/useCharacterGuard.ts
> #359 Fix rerenders after game end

- client/modules/character/pages/CharacterCreatePage.tsx
- client/modules/items/hooks/useItemType.ts
- server/server/character.ts
- shared/character/createCharacterSchema.ts
> #373 Валидация имён

- server/arena/config.ts
- server/arena/magics/__snapshots__/vampirism.test.ts.snap
- server/arena/magics/vampirism.test.ts
- server/arena/magics/vampirism.ts
> feat: change vampirism healing logic

- client/api/serviceShop.ts
- client/modules/serviceShop/components/ServiceShop.tsx
- client/modules/serviceShop/components/ServiceShopDonation.tsx
- client/modules/serviceShop/hooks/useServiceShopDonation.ts
- server/api/invoice.ts
- server/api/payment.ts
- server/arena/ServiceShop.ts
- server/helpers/channelHelper.ts
- server/helpers/donationHelper.ts
- server/models/invoice.ts
- server/models/payment.ts
- server/server/serviceShop.ts
- shared/shared/invoice.ts
> feat: add custom donations

- server/arena/PlayersService/PlayersService.ts
- server/arena/magics/__snapshots__/chainLightning.test.ts.snap
- server/arena/magics/__snapshots__/fireBall.test.ts.snap
- server/arena/magics/__snapshots__/fireRain.test.ts.snap
- server/arena/magics/chainLightning.ts
- server/arena/magics/fireBall.ts
- server/arena/magics/fireRain.ts
> feat: random targets in aoe magics

- server/arena/LogService/utils/format-error.ts
> feat: update magic change fail message

- server/arena/magics/sleep.ts
> fix: fix sleep affect

- server/arena/ActionService.ts
- server/arena/MagicService.ts
- server/arena/OrderService.ts
> fix: better order validation

- client/api/laddet.ts
- client/modules/ladder/components/LadderList.tsx
- client/modules/ladder/components/LadderListItem.tsx
- client/modules/ladder/pages/LadderPage.tsx
- client/modules/lobby/pages/LobbyPage.tsx
- client/router.tsx
- package.json
- server/api/character.ts
- server/arena/CharacterService/CharacterPerformance.ts
- server/arena/CharacterService/CharacterService.ts
- server/arena/CharacterService/utils/calculateLvl.ts
- server/arena/CharacterService/utils/toPublicObject.ts
- server/arena/LadderService/LadderService.ts
- server/cli/addWins.ts
- server/models/character.ts
- server/server/index.ts
- server/server/ladder.ts
- shared/character/characterPublic.ts
- shared/character/characterSchema.ts
> feat: add ladder table

- bun.lock
- client/components/Slider/Slider.tsx
- client/index.css
- client/modules/game/components/GameOrderModal.tsx
- client/modules/game/components/GameOrderProgress.tsx
- client/modules/game/hooks/useGameState.ts
- client/modules/game/store/useGameStore.ts
- client/package.json
- server/arena/RoundService.ts
- server/server/ws/game.ts
- shared/shared/message.ts
> feat: add order progress

- server/arena/Constuructors/LongDmgMagicConstructor.ts
- server/arena/Constuructors/LongMagicConstructor.ts
- server/arena/Constuructors/types.ts
- server/arena/LogService/utils/format-long.ts
- server/arena/LogService/utils/format-message.ts
- server/arena/LogService/utils/join-long-messages.ts
- server/helpers/channelHelper.ts
> feat: show long magic duration

- client/components/Card/Card.css
- client/modules/character/components/CharacterExp.module.css
- client/modules/character/components/CharacterExp.tsx
- client/modules/character/pages/CharacterPage.tsx
- client/utils/formatNumber.ts
- server/arena/CharacterService/CharacterService.ts
- server/arena/CharacterService/utils/calculateLvl.ts
- shared/character/characterSchema.ts
> feat: add character exp progress

- client/.env.example
- client/modules/lobby/hooks/useLobbyHelp.ts
- client/modules/lobby/pages/LobbyPage.tsx
- server/bot/index.ts
- server/helpers/channelHelper.ts
- server/server/ws/lobby.ts
- shared/shared/message.ts
> feat: show lobby help feature if user is not a chat member

- client/api/magic.ts
- client/modules/character/components/CharacterMagicLearnModal.tsx
- client/modules/character/pages/CharacterMagicsPage.tsx
- server/arena/CharacterService/CharacterResources.ts
- server/arena/MagicService.ts
- server/server/magic.ts
- shared/actions/index.ts
> feat: increase magic required lvl

- server/arena/OrderService.ts
- server/arena/PlayersService/PlayerService.ts
- server/server/ws/game.ts
> feat: validate order type

- server/arena/skills/parry.ts
> fix: decrease isParry flag on attack

- client/components/Popup/Popup.css
- client/modules/game/components/GameActionList.tsx
- client/modules/game/components/GameOrderModal.tsx
- client/modules/game/hooks/useGameResult.ts
- client/modules/game/hooks/useGameState.ts
- client/modules/lobby/pages/LobbyPage.tsx
- client/modules/lobby/pages/LobbyPracticePage.tsx
- client/router.tsx
- server/arena/Constuructors/QueueConstrucror.ts
- server/arena/GameService.ts
- server/arena/MatchMakingService.ts
- server/arena/MonsterService/MonsterService.ts
- server/arena/MonsterService/monsters/alpha.ts
- server/arena/MonsterService/monsters/skeleton.ts
- server/arena/MonsterService/monsters/wolf.ts
- server/arena/RewardService.ts
- server/arena/RoundService.ts
- server/helpers/channelHelper.ts
- server/helpers/gameHelper.ts
- server/server/ws/game.ts
- shared/game/index.ts
- shared/item/itemComponent.ts
- shared/shared/message.ts
- shared/shared/monster.ts
> feat: add practice game mode
